### ISSUE TITLE
mod?

### ISSUE THREAD

**Issue by erik-kallen** [hiroshi-manabe/JSDecimal#6]
Hi.

We are considering using this project as part of the runtime library for our C# to JS compiler. It looks very promising, but is there any chance of getting a mod() function implemented?

**Comment by hiroshi-manabe** [comment]
Thank you for your interest. I'll take a look and see if it's easy. Maybe I can take some time this weekend. Of course, your pull requests will always be welcome.

**Comment by erik-kallen** [comment]
Thanks. I think ceil, floor and neg would also be nice additions.

**Comment by erik-kallen** [comment]
It seems like this implementation works for mod:
```
    decimal.prototype.mod = function(other) {
        var a = this.abs(), b = other.abs();
        var r = a.sub(a.div(b).floor().mul(b));
        r.is_minus = this.is_minus;
        return r;
    };

    Decimal.prototype.abs = function() {
        var r = new Decimal(this);
        r.is_minus = false;
        return r;
    };

Depends, though, on the floor function (which I haven't managed to write in a better way than)

    Decimal.prototype.floor = function() {
        return new Decimal(Math.floor(this.toFloat()));
    },

**Comment by hiroshi-manabe** [comment]
Thanks for your code! I used your mod() and abs().
For the floor(), though, I implemented my own version using the existing round().
I also added neg() and ceil().
