### ISSUE TITLE
decimal.Round(new decimal(0.5), 0, decimal.MidpointRounding.ToEven).toFloat() != 1

### ISSUE THREAD

**Issue by bwkiefer** [hiroshi-manabe/JSDecimal#9]
Release: 0.1.17
This returns 0 for any number used for both ToEven and AwayFromZero options.  If you remove the to float call and inspect the sig attribute the final value returns as NaN, sig = [0,0,0,0,NaN].

**Comment by hiroshi-manabe** [comment]
Thank you for reporting the bug.
I introduced a bug as of 0.1.17.

I think I fixed the bug.
By the way, I suppose the correct answer for decimal.Round(new decimal(0.5), 0, decimal.MidpointRounding.ToEven).toFloat() is 0, isn't it?
(Because the nearest even number from 0.5 is 0)

**Comment by bwkiefer** [comment]
Yeah, you're right that it should be zero.  I was using AwayFromZero originally and tried a few cases with ToEven.  I should have double checked the logic of my title, sorry about that.  Glad you got it though.
